version: "3.9"

services:
    uisp:
        container_name: uisp
        image: nico640/docker-unms:1.4.4
        ports:
            - "80:80"
            - "443:443"
            - "2055:2055/udp"
        environment:
            - TZ=America/Chicago
        volumes:
            - ./config:/config
